### ISSUE TITLE
Show options as a list

### ISSUE THREAD

**Issue by gitressa** [dantleech/fink#105]
Is is possible to get all the options listed? `php fink.phar` gives me 

> Not enough arguments (missing: "url")

... and 

> fink [-c|--concurrency CONCURRENCY] [-o|--output OUTPUT] [-D|--no-dedupe] [-x|--max-external-distance MAX-EXTERNAL-DISTANCE] [-k|--insecure] [-m|--max-distance MAX-DISTANCE] [--load-cookies LOAD-COOKIES] [--interval INTERVAL] [-p|--publisher PUBLISHER] [--display-bufsize DISPLAY-BUFSIZE] [--client-max-body-size CLIENT-MAX-BODY-SIZE] [--client-max-header-size CLIENT-MAX-HEADER-SIZE] [--client-redirects CLIENT-REDIRECTS] [--client-timeout CLIENT-TIMEOUT] [--client-security-level CLIENT-SECURITY-LEVEL] [--exclude-url EXCLUDE-URL] [--header HEADER] [--rate RATE] [--include-link INCLUDE-LINK] [-d|--display DISPLAY] [--stdout] [--] <url>...

Perhaps it could output the options as a read-friendly list in stead?

**Comment by dantleech** [comment]
`fink --help` ?

**Comment by gitressa** [comment]
Thanks, that works great. I had a look at README.md before asking here, so perhaps `--help` could be added? I have created a Pull Request for this: #106.

**Comment by gitressa** [comment]
Even when `--help` gets added to the Option list, do you think it is possible for `php fink.phar` to be an alias of `php fink.phar --help`, to list all options, in stead of the current output `fink [-c|--concurrency CONCURRENCY] [-o|--output OUTP ...` (as also inserted above), which is not so reader friendly?
