### ISSUE TITLE
[SOLVED] Name '@cookie_domain@' is not a valid hostname

### ISSUE THREAD

**Issue by gitressa** [dantleech/fink#107]
Using Fink 0.9.0 I was getting `"exception":"Name '@cookie_domain@' is not a valid hostname."`, updating to Fink 0.10.0 fixed this. This issue is just to share that the solution is probably to upgrade, since I was looking everywhere for this error message, with no luck.

Maybe because https://github.com/amphp/artax has been replaced by https://github.com/amphp/http-client?

https://github.com/dantleech/fink/releases/tag/0.10.1
https://github.com/dantleech/fink/pull/92

**Comment by gitressa** [comment]
Closing, since this is just a comment.

**Comment by dantleech** [comment]
Yes exactly, the HTTP client upgrade fixed some issues :muscle:
