### ISSUE TITLE
Generated PHAR does not work on kubernetes cluster due to DNS issues.

### ISSUE THREAD

**Issue by fjgarlin** [dantleech/fink#115]
The `amphp/dns` package had an issue for kubernetes clusters where the URLs could not be resolved. The issue is here: https://github.com/amphp/dns/issues/99

This was resolved here: https://github.com/amphp/dns/commit/8cf2ccc4fa5a97f15b0b11087b22d2b544e45ab2 so from version `v1.2.2` the issue is fixed. 

However, the phar file generated in this library for the tag `0.10.1` does NOT contain that fix, so when using the `fink.phar` file on a kubernetes cluster, you encounter the same problem described in the linked issue.

We could just require that library to be at least `v1.2.2` and then, when tagging the next release, the phar file generated should be usable on k8s.

**Comment by dantleech** [comment]
Thanks, tagged and updated the library in general #117
