### ISSUE TITLE
Query string is added to child links

### ISSUE THREAD

**Issue by dantleech** [dantleech/fink#32]

**Comment by gitressa** [comment]
I can confirm that this is happening.

**Comment by dantleech** [comment]
This is fixed in master: https://github.com/dantleech/fink/blob/master/CHANGELOG.md

Will do another relase this weekend.

**Comment by gitressa** [comment]
Thanks, I am looking forward to it. Have a great weekend.

**Comment by dantleech** [comment]
Fixed in master
