### ISSUE TITLE
Scan password protected pages?

### ISSUE THREAD

**Issue by gitressa** [dantleech/fink#35]
Is it possible to scan password protected pages, or would such a feature be difficult to add?

**Comment by dantleech** [comment]
Yes, you can export a `cookies.txt` ([link](http://www.cookiecentral.com/faq/#3.5))file from your browser using an extension, e.g. https://github.com/rotemdan/ExportCookies

You can then specify it using the `--load-cookies` option.

**Comment by gitressa** [comment]
Thanks for a fast response. My plan is to add fink on a server, trigger it to run once a week via cron, and send a report to a predefined mail-address. So I was hoping there would be a way to automatically login fink (an option like `--username=myuser --password=mypw`. But when I think about it, I guess id's for the username and password fields would be needed as well? It's probably too complicated ... I will see if I can find another way.

**Comment by dantleech** [comment]
We could support HTAUTH and possibly form authentication, but would need more thought (and probably a config file)

On 14 February 2019 23:20:18 CET, gitressa <notifications@github.com> wrote:
>Thanks for a fast response. My plan is to add fink on a server, trigger
>it to run once a week via cron, and send a report to a predefined
>mail-address. So I was hoping there would be a way to automatically
>login fink (an option like `--username=myuser --password=mypw`. But
>when I think about it, I guess id's for the username and password
>fields would be needed as well? It's probably too complicated ... I
>will see if I can find another way.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/dantleech/fink/issues/35#issuecomment-463824842

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gitressa** [comment]
That sounds amazing. Perhaps my client could sponsor you to do this task? Can I PM you somehow to talk more?

**Comment by dantleech** [comment]
Sure, if you are on Twitter I am @dantleech

**Comment by gitressa** [comment]
It turns out logging in fink was a bit more difficult than expected, so I have found another solution.

**Comment by clxmstaab** [comment]
> so I have found another solution.

@gitressa which?

**Comment by gitressa** [comment]
@clxmstaab I ended up extracting the links, and exposing them publicly, without the document text. Did you manage to get the cookie-solution working?

**Comment by clxmstaab** [comment]
> I ended up extracting the links, and exposing them publicly, without the document text. Did you manage to get the cookie-solution working?

yep worked like described.

**Comment by clxmstaab** [comment]
hmm I have to take this one back. it seems the cookies are not passed properly with the request or the session is not resumed because of a different client ip or similar

**Comment by clxmstaab** [comment]
ok figured it out. you can use the cookies-file only from the computer from which you stored it.

its not possible to create the cookie jar on computer A, store it and read it in again on e.g. a linux server.
you need to create the cookie file from the very same ip, because otherwise server side session handling might not continue the http-session because of a IP mismatch

**Comment by gitressa** [comment]
Thanks for sharing your solution @clxmstaab. It seems like the current PR against README is for local usage only, right?

If your example in the previous comment works on a server, with only those two commands, perhaps it would be worth discerning between local browser and server usage in the README, and add all required steps?

**Comment by clxmstaab** [comment]
@gitressa feel free to update the README like you suggested.

**Comment by gitressa** [comment]
I had a look at what's involved in logging into a Drupal site with curl, and it seems like you have to deal with CSRF token field, which seems a bit more involved than I hoped .... So I am probably not going to pursue this solution. But thanks anyway for the README updates.
