### ISSUE TITLE
--exclude-url doesn't seem to work

### ISSUE THREAD

**Issue by gitressa** [dantleech/fink#37]
When I add the `--exclude-url` option mentioned in the README.md I get this message:
`The "--exclude-url" option does not exist. `

**Comment by dantleech** [comment]
This only works on master :)

**Comment by gitressa** [comment]
Thanks for fixing it! I can confirm it works in the latest release. It improves the performance a lot, significantly reducing the number of pages to crawl.

No exclude:
```
Concurrency: 0, Queue size: 0, Failures: 50/885 (5.65%)
Up 28.9 sec, 39.30 r/sec, 152.32 ms/r
```

With exclude:
```
Concurrency: 0, Queue size: 0, Failures: 50/260 (19.23%)
Up 19.4 sec, 7.90 r/sec, 446.38 ms/r
```

I experimented with combining multiple options, like `--exclude-url=comment,order` and `--exclude-url=(comment|order)`, but it seems like I need to add them individually, which does work fine:
```
lando php fink.phar https://example.org \
--max-external-distance=1 \
--exclude-url=comment \
--exclude-url=sort \
--output=linkreport-$(date +\%Y\%m\%d-%H%M).json
```
