### ISSUE TITLE
Exclude querystrings feature request

### ISSUE THREAD

**Issue by gitressa** [dantleech/fink#38]
Would it be possible to exclude certain querystrings, like `order` and `sort`, while following `page`, to allow pagination like `?page=1`, `?page=2`, etc, while not following links like `?page=2&order=title&sort=asc`? If not, it would be great feature :-)
Perhaps something like `--exclude-querystring=order,sort`.

**Comment by dantleech** [comment]
Should be possible already in `master` with `--exclude-url` (multiple options possibe) https://github.com/dantleech/fink#options

**Comment by dantleech** [comment]
Closing as this should already be possible, reopen if necessary :)

**Comment by gitressa** [comment]
You're right, it works in the new release, thanks!
