### ISSUE TITLE
Add PHAR example to README?

### ISSUE THREAD

**Issue by gitressa** [dantleech/fink#41]
Is it worth considering adding tips for PHAR and PHP to the README?

### Installing as a project dependency
`$ composer require dantleech/fink --dev`

### Installing from a PHAR
Download the latest PHAR from the [Releases page](https://github.com/dantleech/fink/releases) (change `0.4.0` to latest version).
`$ wget https://github.com/dantleech/fink/releases/download/0.4.0/fink.phar`

### Usage
Run the command with a single URL to start crawling:
**Composer**
`$ ./vendor/bin/fink https://www.example.com`

**PHP**
`$ php fink.phar https://www.example.com`

**Comment by dantleech** [comment]
Sure, feel free to make a pull request :) (is as easy as editing the README in github)

**Comment by dantleech** [comment]
Although I am also happy to leave it as is for the moment, I would prefer distribute a signed key before providing explicit instructions on installation with tools such as curl or wget.

**Comment by gitressa** [comment]
I agree, it can wait until a signed key is implemented.
