### ISSUE TITLE
SIGINT not defined

### ISSUE THREAD

**Issue by dantleech** [dantleech/fink#42]
See  #39 . Probably happens on systems with out pcntl extension?

**Comment by dantleech** [comment]
@gitressa I have fixed this in master, can you confirm?

**Comment by gitressa** [comment]
It works perfectly now, thanks!

**Comment by dantleech** [comment]
Cool tagged new version :)

**Comment by gitressa** [comment]
Just tried 0.4.1, no more `SIGINT Notices` :)
