### ISSUE TITLE
Add fink to User Agent

### ISSUE THREAD

**Issue by gitressa** [dantleech/fink#46]
It would be great if fink was added to the User Agent in DefaultClient.php

Currently
`const DEFAULT_USER_AGENT = 'Mozilla/5.0 (compatible; Artax)';`

Something like this?
`const DEFAULT_USER_AGENT = 'Mozilla/5.0 (compatible; fink; Artax)';`

**Comment by dantleech** [comment]
Added in #47 which sets the includes `FinkPHP` in the user agent, but also allows setting of custom headers via. `--header="X-MyHeader:  1234abcd`.

**Comment by gitressa** [comment]
Nice, thanks!
