### ISSUE TITLE
Include link text in json result file

### ISSUE THREAD

**Issue by gitressa** [dantleech/fink#49]
Would it be possible to also include the link text of tested links in the json result file (`--output=out.json`)?

It would speed up finding the links, if you update via an editor like CKEditor, and not directly in the HTML source code.

**Comment by gitressa** [comment]
I am still interested in this feature, and even got a use case for it now :-)
Would it be hard to add?

**Comment by dantleech** [comment]
What's your use case? This feature would help finding the dead link, but any more use cases around it would help.

**Comment by gitressa** [comment]
It's basically like I wrote, that if you edit large pages via an editor like CKEditor, and not directly in the HTML source code, it would speed up the process of finding the links, if you are able to search for the link text.

**Comment by dantleech** [comment]
Fixed in #73
