### ISSUE TITLE
Getting status null if no response

### ISSUE THREAD

**Issue by gitressa** [dantleech/fink#50]
If a link like repo.vivaldi.com/stable/deb doesn't return a response, the result is `"status":null`.

**Comment by dantleech** [comment]
hmm, if it doesn't return a response then there can be no response code?

did you also look at the `exception` field?

**Comment by gitressa** [comment]
This is the full result:
```
{
  "url":"http:\/\/repo.vivaldi.com\/stable\/deb",
  "distance":3,
  "referrer":"https:\/\/example.org\/my_path",
  "status":null,
  "request-time":0,
  "exception":"Connection to 'repos.vivaldi.com:8080' failed"
}
```

**Comment by dantleech** [comment]
I think this is working as expected. The timeout was reached, the server did not return a status code.

**Comment by gitressa** [comment]
All right, but then the link won't be included when you run this:
`$ cat report.json| jq -c '. | select(.status==404) | {url: .url, referrer: .referrer}'`

I tried different ways of doing a boolean `OR` but nothing seemed to work, like `select(.status==404|null)` or `select(.status==(404 or null))`. Do you know if something like that is possible? I could run the same command twice, but would like to keep it simple. I might also want to include 5xx's, as well as other HTTP status codes at some point.

**Comment by dantleech** [comment]
I have done this previously:

```
jq -c '. | select(.status!=200) | {url: .url, refferer: .referrer, exception:.exception}'
```

And I'm sure you can do boolean ORs with `jq`.

However, it would also make sense to publsh the internal `success` flag in the results. So you could then filter by `.success!=true`

**Comment by gitressa** [comment]
I also tried that one, but it gives a lot of false positives, because it also catches redirects, like the link below, which actually works fine and gets redirected to https://www.drupal.org/project/boost, but is not a dead link:

`{"url":"http://drupal.org/project/boost","status":403,"refferer":"https://example.org/my_path","exception":null}`

Internal success flag in the results might be a solution, to catch the real dead links, with status 404 or null.

**Comment by dantleech** [comment]
In theory redirects will be followed (by default to maximum of 5 times), so a redirect to a 200 should result in a 200.

**Comment by gitressa** [comment]
You may be right that drupal.org is forbidding the client ... this page is for example available with no redirects via the browser:

`{"url":"https://www.drupal.org/node/2701903","status":403,"exception":null} `

Might an option of adding a bit of delay between requests, like `--request-delay=500` (500 ms) be worth considering, to minimize the risk of fink getting banned by a server?

**Comment by dantleech** [comment]
Yep for sure, there is already `--interval` but that is only the interval between dispatches, and each dispatch is the amout of concurrency available. So a `--throttle` option would be good (new issue?)

**Comment by gitressa** [comment]
#51 has been created :-)

**Comment by gitressa** [comment]
Also, https://github.com/dantleech/fink/issues/53 for an internal `success` flag has been created, as suggested by @dantleech.

**Comment by gitressa** [comment]
Closing this issue, since #53 will probably take care of this issue.
