### ISSUE TITLE
Shouldn't max-external-distance be 0 or 1 as default?

### ISSUE THREAD

**Issue by c33s** [dantleech/fink#62]
i assume that from a user perspective calling fink from the cli would mean that the user wants to scan one site or one site with external link check. its rather uncommon that a user wants to scan the whole net (one link to wikipedia and the whole net it is) :)

sidenote: the default value is not shown in the help text, same for max distance
```
  -x, --max-external-distance=MAX-EXTERNAL-DISTANCE  Limit the external (disjoint) distance from the base URL
  -k, --insecure                                     Allow insecure server connections with SSL
  -m, --max-distance=MAX-DISTANCE                    Maximum link distance from base URL
      --load-cookies=LOAD-COOKIES                    Load cookies from file
      --interval=INTERVAL                            Dispatch request every n milliseconds [default: 10]
```

**Comment by dantleech** [comment]
I'd be happy to accept a pull request to with defaults

**Comment by gitressa** [comment]
A default of `--max-external-distance=1` makes most sense to me, since that is the most typical use case. Scanning internal links only is probably more rare, and scanning the entire internet even rarer.

**Comment by dantleech** [comment]
Fixed
