### ISSUE TITLE
add a box.json for easier self-builds

### ISSUE THREAD

**Issue by c33s** [dantleech/fink#63]

**Comment by dantleech** [comment]
Can it get easier than `box compile`? https://github.com/dantleech/fink/blob/master/.travis.yml#L30

**Comment by c33s** [comment]
its rather that a `box.json` makes it obvious that i can compile with `box`. i noticed it coincidentally by looking in the `composer.json` seeing box as dev requirement. a `box.json` in the project root is more explicit, even if it works without  it.

simply close if you don't like a `box,json`

**Comment by dantleech** [comment]
Closing for now, will add a `box.json` as it becomes necessary (as currently it would just be an empty JSON file).

I added a note in the README to show how to build your own Phar: https://github.com/dantleech/fink/commit/c907a3d840c9e801c5bbfb4231996f073af8a0e5
