### ISSUE TITLE
Allow infinite "report" lines in the cli (currently only 5)

### ISSUE THREAD

**Issue by c33s** [dantleech/fink#65]
tried to capture an image to show both states error and ok (but it was not as easy so the footer and one "result" line are missing):
![2019-03-08 14_43_15-cmder](https://user-images.githubusercontent.com/649209/54032021-be0bba80-41b0-11e9-818c-c89dfab43b9c.png)

full 5 lines:
![2019-03-08 14_50_23-cmder](https://user-images.githubusercontent.com/649209/54032319-8ea97d80-41b1-11e9-8c27-24ddaa8a7e68.png)

currently the user is required to use the report option. errors are only popping up for not even a second and instantly pushed away from the next checked url.
the report formats are both "human unreadable" especially compared to the cli output where the user can easily see the big red errors.
also an unlimited output would allow to pipe the result in a file (including ansi color codes)

**Comment by dantleech** [comment]
:+1:  This would go hand-in-hand with a `progress-format` (or similar) feature, in the meantime there is the `--display-bufsize=5` option which might help you.
