### ISSUE TITLE
Version option doesn't seem to work

### ISSUE THREAD

**Issue by gitressa** [dantleech/fink#80]
I don't get the version as expected, but `Console Tool`:
```
$ php fink.phar --version
Console Tool
$ php fink.phar -V
Console Tool
```
And thanks for releasing 0.7.0, I really appreciate having the link text available.

**Comment by dantleech** [comment]
Fixed in #85 (for the Phar at least)

**Comment by gitressa** [comment]
Thanks!

**Comment by gitressa** [comment]
Thanks! I now get the version:
```
$ php fink.phar --version
Fink Link Checker 0.8.0 (2019-04-07 14:34:58 UTC)
```
