### ISSUE TITLE
Support for non-latin URLs in the dusplay output

### ISSUE THREAD

**Issue by dantleech** [dantleech/fink#81]
e.g.

`https://example.com/кондитерские-и-х/`

is represented as something like `https://example.com/%D0%B1%D0%B0%D0%BA%D0%B0%D0%BB%D0%B5%D1%8F` in the JSON.

We should decode this for display purposes --- and maybe also log the decoded URL to the output?

**Comment by gitressa** [comment]
I am not sure if this is the same issue, but IDN-domains also don't seem to work:
`"exception": "the host gränssnittsdesign.se could not be processed for IDN. Verify that ext/intl is installed for IDN support and that ICU is at least version 4.6."`

**Comment by dantleech** [comment]
Looks like you need to install the PHP INTL extension, e.g. `apt-get install php-intl`

**Comment by gitressa** [comment]
That solved the problem, thanks!

**Comment by dantleech** [comment]
Not sure if this is technically an issue.
