### ISSUE TITLE
End of link concat

### ISSUE THREAD

**Issue by benfruch** [dantleech/fink#96]
Hi dantleech,

Thanks for your plugin, it's very helpful to check my website.

I have a problem with an external link. This link ends with '/' and it isn't correct without this slash.

In the error message, I see that the link has been changed and the trailing slash has been removed during the crawling.

Is this normal?

Thank you in advance

**Comment by dantleech** [comment]
Should be fixed as of https://github.com/dantleech/fink/pull/98 please re-open if not he case
